<?php

define('FLEX_CONTENT_PATH', drupal_get_path('module', 'flex_content'));

/**
 * Implements hook_block_info().
 * @return array
 */
function flex_content_block_info() {
  $blocks = array();
  $blocks['add_content'] = array(
    'info' => t("Add content"),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 * @param string $delta
 * @return array
 */
function flex_content_block_view($delta = '') {
  $blocks = array();

  switch($delta) {
    case 'add_content':
      $blocks['subject'] = t('Flexible content');
      $blocks['content'] = '<a id="flex-link" href="' . base_path() . 'node/add/article" class="fancybox fancybox.iframe">' . t('Add content') . '</a>';
      break;
  }

  return $blocks;
}

/**
 * Implements hook_preprocess_node().
 */
function flex_content_preprocess_node(&$variables) {
  if ($variables['type'] == 'article' && $variables['elements']['#view_mode'] == 'full') {
    drupal_add_css(FLEX_CONTENT_PATH . '/css/flex.css');

    if (!empty($variables['field_flexible_content'])) {
      foreach ($variables['field_flexible_content'] as $key => $field_flexible_content) {
        if ($variables['content']['field_flexible_content'][$key]['entity']['paragraphs_item'][$field_flexible_content['value']]['#bundle'] == 'quote_bundle') {
          $quote = !empty($variables['content']['field_flexible_content'][$key]['entity']['paragraphs_item'][$field_flexible_content['value']]['field_quote_text']['#items'][0]['safe_value'])
            ? $variables['content']['field_flexible_content'][$key]['entity']['paragraphs_item'][$field_flexible_content['value']]['field_quote_text']['#items'][0]['safe_value']
            : NULL;
          $link = !empty($variables['content']['field_flexible_content'][$key]['entity']['paragraphs_item'][$field_flexible_content['value']]['field_quote_link_href']['#items'][0]['safe_value'])
            ? $variables['content']['field_flexible_content'][$key]['entity']['paragraphs_item'][$field_flexible_content['value']]['field_quote_link_href']['#items'][0]['safe_value']
            : NULL;
          $link_text = !empty($variables['content']['field_flexible_content'][$key]['entity']['paragraphs_item'][$field_flexible_content['value']]['field_quote_link_text']['#items'][0]['safe_value'])
            ? $variables['content']['field_flexible_content'][$key]['entity']['paragraphs_item'][$field_flexible_content['value']]['field_quote_link_text']['#items'][0]['safe_value']
            : NULL;

          $variables['content']['field_flexible_content'][$key]['entity']['paragraphs_item'][$field_flexible_content['value']]['field_quote_text'][0]['#markup'] =
            theme('paragraph_quote', array(
                'quote' => $quote,
                'link' => $link,
                'link_text' => $link_text,
              )
            );
          unset($variables['content']['field_flexible_content'][$key]['entity']['paragraphs_item'][$field_flexible_content['value']]['field_quote_link_text']);
          unset($variables['content']['field_flexible_content'][$key]['entity']['paragraphs_item'][$field_flexible_content['value']]['field_quote_link_href']);
        }
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function flex_content_theme() {
  return array(
    'paragraph_quote' => array(
      'variables' => array(
        'quote' => NULL,
        'link' => NULL,
        'link_text' => NULL,
      ),
      'template' => 'templates/paragraph_quote',
    ),
  );
}
