<?php

define('FLEX_CONTENT_DIR', drupal_get_path('module', 'flex_content'));

/**
 * Implements hook_block_info().
 * @return array
 */
function flex_content_block_info() {
  $blocks = array();
  $blocks['add_article_content'] = array(
    'info' => t("Add Article content"),
    'status' => 1,
    'region' => 'sidebar_first',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 * @param string $delta
 * @return array
 */
function flex_content_block_view($delta = '') {
  $blocks = array();

  switch($delta) {
    case 'add_article_content':
      $blocks['subject'] = t('Flexible content');
      $blocks['content'] = '<a id="flex-link" href="' . base_path() . 'node/add/article" class="fancybox fancybox.iframe">' . t('Add content') . '</a>';
      break;
  }

  return $blocks;
}

/**
 * Implements hook_preprocess_node().
 */
function flex_content_preprocess_node(&$variables) {
  if ($variables['type'] == 'article' && $variables['elements']['#view_mode'] == 'full') {
    drupal_add_css(FLEX_CONTENT_DIR . '/assets/css/flex.css');
    drupal_add_css(FLEX_CONTENT_DIR . '/assets/owl-carousel/owl.carousel.css');
    drupal_add_css(FLEX_CONTENT_DIR . '/assets/owl-carousel/owl.theme.css');
    drupal_add_js(FLEX_CONTENT_DIR . '/assets/owl-carousel/owl.carousel.js');
    drupal_add_js(FLEX_CONTENT_DIR . '/assets/js/flex.js');
  }
}

/**
 * Implements hook_theme().
 */
function flex_content_theme() {
  return array(
    'field__field_slider__text_slider' => array(
      'render element' => 'content',
      'template' => 'field--field-slider--text-slider',
      'path' => FLEX_CONTENT_DIR . '/templates',
    ),
    'paragraphs_item__quote_bundle' => array(
      'render element' => 'content',
      'template' => 'paragraphs-item--quote-bundle',
      'path' => FLEX_CONTENT_DIR . '/templates',
    ),
  );
}
